lang: en

project:
  type: website
  render:
    - "*.qmd"
    - "!CLAUDE.md"
    - "!README.md"

website:
  title: "Keefe Reuther"
  image: "assets/logosimple.webp"
  reader-mode: true
  open-graph: false
  favicon: "assets/logosimple.webp"
  site-url: https://keefereuther.com
  repo-url: https://github.com/keefereuther/quarto_website
  page-navigation: false
  bread-crumbs: false
  navbar:
    logo: assets/logosimple.webp
    right:
      - text: "About"
        menu:
          - href: docs/about/keefe/index.qmd
            text: Keefe Reuther
          - href: docs/about/contact/index.qmd
            text: Contact Us
      - href: docs/teaching/index.qmd
        text: Teaching
      - text: "Scholarship"
        menu:
          - href: docs/scholarship/publications.qmd
            text: Publications
          - href: docs/scholarship/presentations.qmd
            text: Presentations
          - href: docs/scholarship/index.qmd
            text: Projects
      - text: "GenAI"
        menu:
          - href: docs/genai/tools/index.qmd
            text: Tools & Resources
          - href: docs/genai/community/index.qmd
            text: Community
      - href: docs/blog/index.qmd
        text: Blog

  page-footer:
    border: true
    left: |
      [![](/assets/ucsdbioweb.png){fig-alt="UCSD Bio" width=100px}](https://biosci.ucsd.edu) 
      [![](/assets/ebewebbug.png){fig-alt="UCSD EBE" width=100px}](https://biology.ucsd.edu/research/academic-departments/ebe/)
      [![](/assets/UCSanDiegoLogo-BlueGold.png){fig-alt="UCSD" width=100px}](https://ucsd.edu)
    right:
      - text: "This site combines my original content with GAI-aided portions from tools like ChatGPT. All content is curated and verified by me, Keefe Reuther."
      - icon: github
        href: https://github.com/keefereuther
        aria-label: Keefe Reuther GitHub
      - text: "License"
        href: license.qmd

format:
  html:
    page-layout: article
    include-before-body: _includes/skip-nav.html
    theme:
      light: minty
      dark: quartz
    css: styles.css
    toc: false
    fontsize: 1.2em
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px

editor: visual

