project:
  type: website

website:
  title: "The Reuther Lab"
  image: "logo_dark.webp"
  reader-mode: true
  open-graph: true
  favicon: "logo_dark.webp"
  navbar:
    logo: logo_dark.webp
    right:
      - text: "About"
        menu: 
          - href: about.qmd
            text: Keefe Reuther
          - href: people.qmd
            text: People
          - href: contact.qmd
            text: Contact Us
      - text: "Our Work"
        menu: 
          - href: teaching.qmd
            text: Teaching
          - href: scholarship.qmd
            text: Scholarship
      - href: blog.qmd
        text: Blog

  page-footer:
    border: true
    left: |
      [![](/ucsdbioweb.png){fig-alt="UCSD Bio" width=100px}](https://biosci.ucsd.edu) 
      [![](/ebewebbug.png){fig-alt="UCSD EBE" width=100px}](https://biology.ucsd.edu/research/academic-departments/ebe/)
      [![](/UCSanDiegoLogo-BlueGold.png){fig-alt="UCSD" width=100px}](https://ucsd.edu)
    right:
      - icon: github
        href: https://github.com/keefereuther
        aria-label: Keefe Reuther GitHub
      - text: "License"
        href: license.qmd

format:
  html:
    page-layout: article
    theme:
      light: minty
      dark: cyborg
    css: styles.css
    toc: true
    fontsize: 1.2em

editor: visual

