[build]
  command = 'curl -sL https://quarto.org/download/latest/quarto-linux-amd64.tar.gz | tar -xz && export PATH="$PWD/$(ls -d quarto-*/bin | head -1):$PATH" && quarto render .'
  publish = "_site/"

[[redirects]]
  from = "/docs/scholarship/index.html"
  to = "/docs/scholarship/publications.html"
  status = 301

[[redirects]]
  from = "/docs/scholarship/projects/simulation.html"
  to = "/docs/genai/tools/index.html#using-simulation-to-learn-biology"
  status = 301

[[redirects]]
  from = "/docs/scholarship/projects/genaischolarship.html"
  to = "/docs/genai/tools/index.html"
  status = 301

[[redirects]]
  from = "/docs/scholarship/projects/assessment.html"
  to = "/docs/scholarship/papers/saberwest2023reuther.html"
  status = 301

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
